If image bucket is unavailable, download svg file
yosoyubik/canvas pull request #30
Opened 2021-12-09 02:29 UTC by johnhyde

This opens up the "Export canvas" to everyone.

In the future, perhaps we should render it to a PNG, as most image hosting sites like imgur don't accept SVGs.

2021-12-09 07:40 UTC, johnhyde commented
Ok, I've added PNG export as a menu option

2021-12-11 07:02 UTC, yosoyubik commented
Downloading SVG and PNG files works fine but If an S3 bucket is available, exporting to PNG exports [this](https://yosoyubik.fra1.digitaloceanspaces.com/zod/~2021.12.11..06.57.42-hom.png)? Not sure what

2021-12-11 07:31 UTC, yosoyubik requested changes
I got it to work with the suggested changes I posted—let me know what you think

2021-12-11 07:31 UTC, yosoyubik commented on ui/src/components/OptionsMenu.svelte
> +  }
```suggestion
    switch (fileExtension) {
      case 'svg':
        data = svgData;
        dataUrl = generateDataUrl(svgData, 'image/svg+xml');
        mimetype = 'image/svg+xml';
        break;
      case 'png':
        ({ dataUrl } = await renderSvgToPng(svgData));
        data = dataUrl;
        mimetype = 'image/png';
        break;
      default:
        throw new Error(`Unknown file extension: ${fileExtension}`);
    }
    const timestamp = dateToDa(new Date());
    const fileName = `${window.ship}/${timestamp}-${name}.${fileExtension}`;
    if (canUploadFilesToStorage()) {
      try {
        await uploadFileToStorage(data, fileName, mimetype);
      } catch (e) {
        console.error(
          `Encountered error uploading to s3: ${e.message}\nDownloading svg file`,
          e
        );
      }
    } else {
      downloadFile(dataUrl, fileName);
    }
```

2021-12-11 07:31 UTC, yosoyubik commented on ui/src/components/OptionsMenu.svelte
> +    });
```suggestion
    const body =
      mimetype !== 'image/png'
        ? data
        : Buffer.from(data.replace(/^data:image\/\w+;base64,/, ''), 'base64');

    const bucket = $store.s3.configuration.currentBucket;
    const params = new PutObjectCommand({
      Bucket: bucket,
      Key: fileName,
      Body: body,
      ACL: 'public-read',
      ContentEncoding: mimetype === 'image/png' ? 'base64' : undefined,
      ContentType: mimetype
    });
```

2021-12-11 08:05 UTC, yosoyubik requested changes

2021-12-11 23:15 UTC, johnhyde commented
Changes implemented

2021-12-12 05:11 UTC, merged